services:
  app:
    build:
      context: .
      # args:
      #   DATABASE_URL: ${DATABASE_URL}
      #   DIRECT_URL: ${DIRECT_URL}
      #   NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      #   CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      #   ADMIN_USER_ID: ${ADMIN_USER_ID}
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - net

networks:
  net:
    driver: bridge
